### ISSUE TITLE
Frontend is not compatible with other versions of Python

### ISSUE THREAD

**Issue by SalazarPeverelll** [code-philia/time-travelling-visualizer#1]
When building front-end by option 2, the fetch of repository 'local_execution_config_python' will fail if user is using other python versions instead of 3,7.

Since python repositories are not necessary needed in front-end, could the fetch of those repositories be removed to improve the scalability?

![Error_Message](https://github.com/code-philia/time-travelling-visualizer/assets/52120463/5936d5d5-680e-4cba-addd-25444a736e12)

**Comment by Yvonnefanf** [comment]
fixed, and removed potential build python process from BUILD files.
