### ISSUE TITLE
new functions to add

### ISSUE THREAD

**Issue by SalazarPeverelll** [code-philia/time-travelling-visualizer#18]
1. a view to better compare code and comment
2. remove "comment" part in displaying the code.
3. add query mode: nl query --> using an agent(LLM) to convert the query into (sql) query --> display query results.

**Comment by llmhyy** [comment]
Close this issue and create three new issues, each of whose names shall be very clear @SalazarPeverelll

**Comment by SalazarPeverelll** [comment]
function 1 is merged into issue #34
function 2 is solved
function 3 is merged into issue#30
