### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by llmhyy** [code-philia/time-travelling-visualizer#27]
(visualizer) D:\code-space\time-travelling-visualizer\Tool\server>python server.py
Traceback (most recent call last):
  File "server.py", line 14, in <module>
    from utils import get_comparison_coloring, get_coloring, getVisError, update_epoch_projection, initialize_backend, add_line, getConfChangeIndices, getContraVisChangeIndices, getContraVisChangeIndicesSingle,getCriticalChangeIndices, update_custom_epoch_projection, highlight_epoch_projection
  File "D:\code-space\time-travelling-visualizer\Tool\server\utils.py", line 502, in <module>
    from transformers import (WEIGHTS_NAME, AdamW, get_linear_schedule_with_warmup,
ModuleNotFoundError: No module named 'transformers'

**Comment by SalazarPeverelll** [comment]
fixed by commit 590017c

**Comment by SalazarPeverelll** [comment]
fixed by commit 590017c
