### ISSUE TITLE
User Configuration DDL:[2024/6/3] 

### ISSUE THREAD

**Issue by llmhyy** [code-philia/time-travelling-visualizer#28]
Create a menu to record user's configuration, e.g., dataset path, model path, and other preference.

**Comment by SalazarPeverelll** [comment]
1.  Refer to the VSCode to design and change the style of tool.
2.  Create a menu to record user's configuration, e.g., dataset path, model path, and other preference.

**Comment by SalazarPeverelll** [comment]
issue merged into issue#35
